spring:
  jpa.hibernate.ddl-auto: create-drop
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/smalltasks-db
    username: smalltasks
    password: smalltasks

web:
  url: http://localhost:9000
